export { default as NotFound } from './error/404/NotFound'
export { default as Home } from './home/Home'
export { default as Homestudent } from './home/Homestudent'
export { default as Hometrainer } from './home/Hometrainer'
export { default as Uploadtrainer } from './home/Uploadtrainer'
export { default as Kontentrainer } from './home/Kontentrainer'
export { default as UserRegister } from './auth/register/user'
export { default as UserLogin } from './auth/login/login'
export { default as UserRegisterMember } from './auth/register/usermember'
export { default as UserRegisterMontir } from './auth/register/usermontir'
export { default as UserRegisterPerusahaan } from './auth/register/userperusahaan'

